package cli

import (
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"strings"
)

// configToml is the schema we write to .hookwave.toml. Kept tiny
// on purpose — the goal is to remember just enough so subsequent
// `hookwave listen` calls in this repo know which source + port
// to use without flags.
type configToml struct {
	SourceID  string
	Provider  string
	IngestURL string
	LocalPort int
}

func writeConfigToml(path string, c configToml) error {
	const tmpl = `# Hookwave project config — checked into your repo.
# Used by ` + "`" + `hookwave listen` + "`" + ` and friends to remember which source to bind to.
[source]
id        = "%s"
provider  = "%s"
ingest_url = "%s"

[local]
port      = %d
`
	body := fmt.Sprintf(tmpl, c.SourceID, c.Provider, c.IngestURL, c.LocalPort)
	return os.WriteFile(path, []byte(body), 0o644)
}

// writeHandlerStub drops a starter file at handlers/<provider>.<ext>.
// Returns the path written, or "" if the file already existed and
// `force` was false.
func writeHandlerStub(dir, provider, lang string, force bool) (string, error) {
	ext, body, err := stubFor(provider, lang)
	if err != nil {
		return "", err
	}
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return "", err
	}
	path := filepath.Join(dir, provider+"."+ext)
	if !force {
		if _, err := os.Stat(path); err == nil {
			return "", nil
		} else if !errors.Is(err, fs.ErrNotExist) {
			return "", err
		}
	}
	if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
		return "", err
	}
	return path, nil
}

func stubFor(provider, lang string) (string, string, error) {
	switch strings.ToLower(lang) {
	case "typescript":
		return "ts", tsHandler(provider), nil
	case "javascript":
		return "js", jsHandler(provider), nil
	case "python":
		return "py", pyHandler(provider), nil
	case "go":
		return "go", goHandler(provider), nil
	}
	return "", "", fmt.Errorf("unsupported handler language %q", lang)
}

func tsHandler(provider string) string {
	return `// Auto-generated by ` + "`" + `hookwave init` + "`" + `. Edit freely.
//
// Plug this into your framework — e.g. Express:
//   app.post("/", express.raw({ type: "*/*" }), handle` + capitalize(provider) + `Webhook);
//
// In dev: ` + "`" + `hookwave listen` + "`" + ` forwards events from Hookwave to your localhost.
// In prod: point ` + provider + ` at the Hookwave ingest URL printed by the CLI.

import type { IncomingMessage, ServerResponse } from "node:http";

export async function handle` + capitalize(provider) + `Webhook(req: IncomingMessage, res: ServerResponse): Promise<void> {
  const eventId = req.headers["x-hookwave-event-id"];
  const sourceId = req.headers["x-hookwave-source-id"];
  console.log("[` + provider + `] event", eventId, "from", sourceId);

  // TODO: parse req body, do real work.

  res.statusCode = 200;
  res.end("ok");
}
`
}

func jsHandler(provider string) string {
	return `// Auto-generated by ` + "`" + `hookwave init` + "`" + `. Edit freely.
//
// In dev: ` + "`" + `hookwave listen` + "`" + ` forwards events here from Hookwave.
// In prod: point ` + provider + ` at the Hookwave ingest URL printed by the CLI.

export async function handle` + capitalize(provider) + `Webhook(req, res) {
  const eventId = req.headers["x-hookwave-event-id"];
  console.log("[` + provider + `] event", eventId);
  res.statusCode = 200;
  res.end("ok");
}
`
}

func pyHandler(provider string) string {
	return `# Auto-generated by ` + "`" + `hookwave init` + "`" + `. Edit freely.
#
# Plug this into your framework — e.g. FastAPI:
#   @app.post("/")
#   async def hook(request: Request) -> Response:
#       return await handle_` + provider + `_webhook(request)
#
# In dev: ` + "`" + `hookwave listen` + "`" + ` forwards events from Hookwave to your localhost.
# In prod: point ` + provider + ` at the Hookwave ingest URL printed by the CLI.

from typing import Any


async def handle_` + provider + `_webhook(request: Any) -> Any:
    event_id = request.headers.get("x-hookwave-event-id")
    print(f"[` + provider + `] event {event_id}")
    return {"status": "ok"}
`
}

func goHandler(provider string) string {
	return `// Auto-generated by ` + "`" + `hookwave init` + "`" + `. Edit freely.
//
// In dev: ` + "`" + `hookwave listen` + "`" + ` forwards events here from Hookwave.
// In prod: point ` + provider + ` at the Hookwave ingest URL printed by the CLI.

package handlers

import (
	"log"
	"net/http"
)

func Handle` + capitalize(provider) + `Webhook(w http.ResponseWriter, r *http.Request) {
	eventID := r.Header.Get("X-Hookwave-Event-Id")
	log.Printf("[` + provider + `] event %s", eventID)
	w.WriteHeader(http.StatusOK)
	_, _ = w.Write([]byte("ok"))
}
`
}

func capitalize(s string) string {
	if s == "" {
		return s
	}
	return strings.ToUpper(s[:1]) + s[1:]
}
